set_property SRC_FILE_INFO {cfile:F:/ax7010/2017/course_s1/11_linux_base/linux_base.srcs/constrs_1/new/hdmi_out.xdc rfile:../../../linux_base.srcs/constrs_1/new/hdmi_out.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:F:/ax7010/2017/course_s1/11_linux_base/linux_base.srcs/constrs_1/new/led.xdc rfile:../../../linux_base.srcs/constrs_1/new/led.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:F:/ax7010/2017/course_s1/11_linux_base/linux_base.srcs/constrs_1/new/key.xdc rfile:../../../linux_base.srcs/constrs_1/new/key.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports TMDS_clk_p]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports {TMDS_data_p[2]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports hdmi_oen]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports hdmi_ddc_scl_io]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports hdmi_ddc_sda_io]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {leds_tri_o[0]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {leds_tri_o[1]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {leds_tri_o[2]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {leds_tri_o[3]}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {btns_tri_i[0]}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {btns_tri_i[1]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {btns_tri_i[2]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports {btns_tri_i[3]}]
